services:
  node-service:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - ml-service
    networks:
      - app-network

  ml-service:
    build:
      context: ./ml
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
